// Business configuration
export const BUSINESS = {
  name: "Top Choice Concrete",
  shortName: "TC",
  phone: "(919) 574-5043",
  email: "topchoiceconcrete92@gmail.com",
  tagline: "Quality Residential Concrete — Benson, NC",
};

// Status badge config (light theme)
export const STATUS_CONFIG = {
  draft:    { label: "Draft",    bg: "#F0EFEB", color: "#777777", border: "#E0DCD0", dot: "#AAAAAA" },
  sent:     { label: "Sent",     bg: "#E3F0FA", color: "#2B6CB0", border: "#BDD6EE", dot: "#5B9BD5" },
  accepted: { label: "Accepted", bg: "#E8F5E9", color: "#2E7D32", border: "#A5D6A7", dot: "#2E7D32" },
  declined: { label: "Declined", bg: "#FFEBEE", color: "#C62828", border: "#EF9A9A", dot: "#C62828" },
  expired:  { label: "Expired",  bg: "#FFF8E1", color: "#E6A817", border: "#FFE082", dot: "#F9A825" },
};

// Terms & conditions
export const DEFAULT_TERMS = [
  "This estimate is valid for 30 days from the date issued.",
  "A 50% deposit is required to schedule the project.",
  "Remaining balance is due upon completion of work.",
  "Price includes all materials, labor, and standard cleanup.",
  "Any changes to scope after acceptance may result in additional charges.",
  "Top Choice Concrete is fully licensed and insured.",
  "Work is guaranteed for 2 years against structural defects.",
  "Customer is responsible for obtaining any required permits.",
];

// Line item presets
export const LINE_ITEM_PRESETS = [
  { desc: "Remove existing concrete", unit: "sqft", rate: 3.5 },
  { desc: 'New 4" concrete slab w/ fiber mesh', unit: "sqft", rate: 12.0 },
  { desc: 'New 4" concrete slab w/ rebar', unit: "sqft", rate: 14.0 },
  { desc: "Broom finish", unit: "sqft", rate: 0.75 },
  { desc: "Stamped concrete finish", unit: "sqft", rate: 4.5 },
  { desc: "Color hardener application", unit: "sqft", rate: 1.25 },
  { desc: "Sealer application (2 coats)", unit: "sqft", rate: 1.0 },
  { desc: "Expansion joints", unit: "ea", rate: 45.0 },
  { desc: "Rebar grid layout", unit: "sqft", rate: 1.5 },
  { desc: "Cool deck coating", unit: "sqft", rate: 6.0 },
  { desc: "Epoxy coating (flake)", unit: "sqft", rate: 5.5 },
  { desc: "Coping — bullnose edge", unit: "lnft", rate: 22.0 },
  { desc: "Garage floor overlay", unit: "sqft", rate: 8.0 },
  { desc: "Form and grade prep", unit: "sqft", rate: 2.0 },
];

// Seed estimates with NC addresses
export const SEED_ESTIMATES = [
  {
    id: "EST-2026-001",
    status: "draft",
    customer: "Mike Thompson",
    address: "142 Oak Ridge Dr, Benson NC",
    phone: "(919) 555-0147",
    email: "mike.t@email.com",
    created: "2026-02-25",
    expires: "2026-03-27",
    items: [
      { id: 1, desc: "Remove existing driveway (approx 600 sqft)", qty: 600, unit: "sqft", rate: 3.5 },
      { id: 2, desc: 'New 4" concrete driveway w/ fiber mesh', qty: 600, unit: "sqft", rate: 12.0 },
      { id: 3, desc: "Broom finish", qty: 600, unit: "sqft", rate: 0.75 },
      { id: 4, desc: "Expansion joints", qty: 8, unit: "ea", rate: 45.0 },
    ],
    notes: "Customer wants driveway replaced before summer. Access from side yard. Existing driveway has significant cracking.",
    images: ["driveway_front.jpg", "crack_detail.jpg"],
    acceptedAt: null,
    declinedAt: null,
    declineReason: null,
  },
  {
    id: "EST-2026-002",
    status: "sent",
    customer: "Sarah Chen",
    address: "88 Magnolia Ct, Clayton NC",
    phone: "(919) 555-0293",
    email: "sarah.chen@email.com",
    created: "2026-02-20",
    expires: "2026-03-22",
    items: [
      { id: 1, desc: 'Patio slab 16x20 — 4" w/ rebar', qty: 320, unit: "sqft", rate: 14.0 },
      { id: 2, desc: "Stamped concrete finish (ashlar slate)", qty: 320, unit: "sqft", rate: 4.5 },
      { id: 3, desc: "Color hardener — sandstone", qty: 320, unit: "sqft", rate: 1.25 },
      { id: 4, desc: "Sealer (2 coats)", qty: 320, unit: "sqft", rate: 1.0 },
    ],
    notes: "Stamped patio off back door. Customer chose ashlar slate pattern with sandstone color. Need to coordinate with landscaper.",
    images: ["backyard_area.jpg"],
    acceptedAt: null,
    declinedAt: null,
    declineReason: null,
  },
  {
    id: "EST-2026-003",
    status: "accepted",
    customer: "James Rodriguez",
    address: "310 Elm St, Smithfield NC",
    phone: "(919) 555-0481",
    email: "j.rodriguez@email.com",
    created: "2026-02-10",
    expires: "2026-03-12",
    items: [
      { id: 1, desc: "Sidewalk — 4' wide x 60' long, 4\"", qty: 240, unit: "sqft", rate: 11.0 },
      { id: 2, desc: "Broom finish", qty: 240, unit: "sqft", rate: 0.75 },
    ],
    notes: "Front walkway from driveway to porch. Straight run, minimal grading needed.",
    images: [],
    acceptedAt: "2026-02-15T14:30:00Z",
    declinedAt: null,
    declineReason: null,
  },
  {
    id: "EST-2026-004",
    status: "expired",
    customer: "Linda Park",
    address: "55 Cypress Bend, Four Oaks NC",
    phone: "(919) 555-0612",
    email: "lindap@email.com",
    created: "2026-01-15",
    expires: "2026-02-14",
    items: [
      { id: 1, desc: "Garage floor overlay", qty: 440, unit: "sqft", rate: 8.0 },
      { id: 2, desc: "Epoxy coating (flake)", qty: 440, unit: "sqft", rate: 5.5 },
    ],
    notes: "Garage floor resurfacing with epoxy flake finish. Customer hasn't responded.",
    images: ["garage_floor.jpg"],
    acceptedAt: null,
    declinedAt: null,
    declineReason: null,
  },
  {
    id: "EST-2026-005",
    status: "declined",
    customer: "Tom & Angela Wright",
    address: "201 Live Oak Ln, Benson NC",
    phone: "(919) 555-0734",
    email: "wrights@email.com",
    created: "2026-02-01",
    expires: "2026-03-03",
    items: [
      { id: 1, desc: "Pool deck — 800 sqft, 4\" w/ rebar", qty: 800, unit: "sqft", rate: 15.0 },
      { id: 2, desc: "Cool deck coating", qty: 800, unit: "sqft", rate: 6.0 },
      { id: 3, desc: "Coping — bullnose edge", qty: 120, unit: "lnft", rate: 22.0 },
    ],
    notes: "Pool deck replacement. Declined — went with pavers instead.",
    images: ["pool_area.jpg", "existing_deck.jpg"],
    acceptedAt: null,
    declinedAt: "2026-02-10T10:15:00Z",
    declineReason: "Went with another company",
  },
  {
    id: "EST-2026-006",
    status: "draft",
    customer: "Robert & Diane Fisher",
    address: "478 Creekside Dr, Dunn NC",
    phone: "(910) 555-0388",
    email: "fisher.rd@email.com",
    created: "2026-02-26",
    expires: "2026-03-28",
    items: [
      { id: 1, desc: "Foundation repair — crack injection", qty: 12, unit: "lnft", rate: 85.0 },
      { id: 2, desc: "Waterproof sealant application", qty: 120, unit: "sqft", rate: 4.0 },
    ],
    notes: "Hairline cracks in basement foundation wall. Needs injection and sealing. Inspect for water damage.",
    images: ["foundation_crack.jpg"],
    acceptedAt: null,
    declinedAt: null,
    declineReason: null,
  },
  {
    id: "EST-2026-007",
    status: "sent",
    customer: "Patricia Owens",
    address: "92 Harvest Moon Rd, Clayton NC",
    phone: "(919) 555-0856",
    email: "p.owens@email.com",
    created: "2026-02-22",
    expires: "2026-03-24",
    items: [
      { id: 1, desc: 'Retaining wall — 40\' x 3\' — 6" reinforced', qty: 120, unit: "sqft", rate: 28.0 },
      { id: 2, desc: "Form and grade prep", qty: 120, unit: "sqft", rate: 2.0 },
      { id: 3, desc: "Drainage gravel backfill", qty: 5, unit: "cuyd", rate: 95.0 },
    ],
    notes: "Retaining wall along back property line. Slope is moderate. Customer wants smooth finish. Need to check for utilities before digging.",
    images: ["backyard_slope.jpg", "property_line.jpg"],
    acceptedAt: null,
    declinedAt: null,
    declineReason: null,
  },
];
